LANG_ID = "en_us"
LANG_DESC = "USA English"
LANG_RESOURCE = {
	"LANG_RESOURCE_EXAMPLE" : "This is a example",
	/* begin */
	"NOT_CHOOSE_ATTACH" : "Please choose a destination file",
	"LOGIN_FAILED" : "Login failed",
	"MAILBOX_INBOX" : "Inbox",
	"MAILBOX_SENT" : "Sent",
	"MAILBOX_DRAFTS" : "Drafts",
	"MAILBOX_TRASH" : "Trash",
	"MAILBOX_JUNK" : "Junk",
	"CONFIRM_CLEAN_TRASH" : "Sure to clean the trash?",
	"CLEAN_TRASH" : "Clean",
	"SAVED" : "Save Successfully",
	"WRONG_VERIFIED_PASSWORD" : "Verified password is not equal with first one",
	"PASSWORD_CHANGED_NEED_RELOGIN" : "Change password successfully. Please relogin",
	"PASSWORD_CHANGED_FAILED_NEED_RETRY" : "Change password failed",
	"EMPTY_ALIAS" : "Alias can not be empty",
	"CHANGE_ALIAS_OK" : "Change alias successfully",
	"CHANGE_ALIAS_FAILED" : "Change alias failed",
	"ADMINISTRATOR_DESC" : "Administrator",
	"USER_DESC" : "User",
	"DISABLED_ID_DESC" : "Disabled",
	"UNKNOWN_ID_DESC" : "Unknown",
	"YES" : "Yes",
	"NO" : "No",
	"CREATE" : "Create",
	"FAILED" : "failed",
	"WHOSE_FOLDER" : "'s folder",
	"REMOVE_FOLDER_WARNING" : "Sure to delete the folder?",
	"NOSELECTED_FOLDER_WARNING" : "No choose any folder",
	"MORETHANONE_FOLDER_WARNING" : "Can not choose more than one folder",
	"FOLDER" : "Folder",
	"OK" : "Ok",
	"CANCEL" : "Cancel",
	"REMOVE" : "Remove",
	"NEW_FOLDER" : "New Folder",
	"REMOVE_FOLDER" : "Remove Folder",
	"MAILS" : "mails",
	"REMOVE_THIS_FOLDER_WARNING" : "Sure to remove the folder?",
	"NOSELECTED_MAIL_WARNING" : "Please choose the mail firstly",
	"REPLAY_ONLY_ONE_MAIL_WARNING" : "Can not replay more than one mail once",
	"FORWARD_ONLY_ONE_MAIL_WARNING" : "Can not forward more than one mail once",
	"NOSELECTED_COPY_MAIL_WARNING" : "Please choose the mail to copy firstly",
	"NOSELECTED_MOVE_MAIL_WARNING" : "Please choose the mail to move firstly",
	"NO_SUBJECT" : "No Subject",
	"MAIL_GROUP_DESC" : "Group",
	"ACTIVE_ID_DESC" : "Active",
	"APPEND_ID_TO_GROUP_DESC" : "Append ID",
	"APPEND_ID_TO_MAILGROUP_ERROR" : "Fail to append ID to group",
	"DELETE_ID_FROM_MAILGROUP_ERROR" : "Fail to remove ID from group",
	"DELETE_ID_FROM_MAILGROUP_WARNING" : "Sure to remove ID from the group?",
	"PASS_DESC" : "Pass",
	"REJECTED_DESC" : "Rejected",
	"UNBOUND_IP_DESC" : "Unbound IP",
	"EDIT_ID_DESC" : "Edit ID",
	"APPEND_ID_DESC" : "Append ID",
	"REMOVE_ID_ERROR" : "Remove ID failed",
	"REMOVE_ID_WARNING" : "Sure to remove？",
	"VERIFY_PASSWORD_ERROR" : "Passwod is not equal with the verified one",
	"APPEND_ID_ERROR" : "Append ID failed",
	"EDIT_ID_ERROR" : "Edit ID failed",
	"LOADING_FAILED" : "Loading failed",
	"ATTACHMENT_NUM" : " attachments",
	"EVENT_SUMMARY_DESC" : "Summary:",
	"EVENT_LOCATION_DESC" : "Location:",
	"EVENT_CREATED_DESC" : "Created:",
	"EVENT_MODIFIED_DESC" : "Modified:",
	"EVENT_START_DESC" : "Start:",
	"EVENT_END_DESC" : "End:",
	"EVENT_ORGNIZER_DESC" : "Orgnizer:",
	"EVENT_INVITEE_DESC" : "Invitee:",
	"EVENT_REQUEST" : "Event Request",
	"EVENT_RESPONSE" : "Event Response",
	"COPY_MAIL_ONGOING" : "Copying mail is ongoing, please wait...",
	"MOVE_MAIL_ONGOING" : "Moving mail is ongoing, please wait...",
	"NON_SAVED_DRAFT_WARNING" : "Unsaved draft",
	"ADDRESS_BOOK" : "Address Book",
	"MAIL_FROM_DESC" : "From:",
	"MAIL_TO_DESC" : "To:",
	"MAIL_CC_DESC" : "CC:",
	"MAIL_DATE_DESC" : "Date:",
	"MAIL_SUBJECT_DESC" : "Subject:",
	"SAVE_DRAFT_ONGOING" : "Saving draft is ongoing...",
	"SAVE_DRAFT_ERROR" : "Save draft failed",
	"SAVE_DRAFT_ERROR_FOR_HUGE_SIZE" : "Save draft failed for huge size",
	"SAVE_DRAFT_OK" : "Save draft successfully",
	"SEND_MAIL_ONGOING" : "Sending mail is ongoing...",
	"SEND_MAIL_FAILED" : "Send mail failed",
	"SEND_MAIL_FAILED_FOR_HUGE_SIZE" : "Send mail failed for huge size",
	"SEND_MAIL_OK" : "Send mail successfully",
	"EMPTY_MAIL_TO_WARNING" : "Empty address of mail to",
	"EMPTY_SUBJECT_WARNING" : "Empty subject, continue？",
	"SAVE_MAIL_TO_SENT_FOLDER_ONGOING" : "Saving mail to sent folder is ongoing...",
	"SAVE_MAIL_TO_SENT_FOLDER_FAILED" : "Saving mail to sent folder failed",
	"SAVE_MAIL_TO_SENT_FOLDER_OK" : "Saving mail to sent folder successfully",
	"QUIT_WEB_WARNING_FOR_PROCESSING_MAIL" : "Sending mail is onging, sure to quit?",
	"QUIT_WEB_WARNING_FOR_UNSAVED_UNSENT_MAIL" : "Unsaved or unsent mail, sure to quit?",
	"QUIT_WEB_WARNING" : "Sure to quit?",
	"DEFAULT_LEVEL" : "Default Level",
	"NO_NEED_REVIEW_LEVEL" : "No need review",
	"NEED_REVIEW_LEVEL" : "Need review",
	"CREATE_LEVEL_FAILED" : "Create level failed",
	"UPDATE_LEVEL_FAILED" : "Update level failed",
	"DELETE_LEVEL_FAILED" : "Delete level failed",
	"SET_DEFAULT_LEVEL_FAILED" : "Set default level failed",
	"APPEND_LEVEL_DESC" : "Create Level",
	"EDIT_LEVEL_DESC" : "Edit Level",
	"DELETE_DEFAULT_LEVEL_ERROR" : "Cannot delete default level",
	"DELETE_LEVEL_WARNING" : "Sure to delete?",
	"ILLEGALS_LEVEL_NAME_CHAR" : "Illegal character",
	"MAX_MAIL_SIZE_WARNING" : "Maximum mail size cannot exceed ",
	"MAX_MAILBOX_SIZE_WARNING" : "Maximum mailbox size cannot exceed ",
	/* end */
	"LANG_RESOURCE_LAST_PLACE_HOLDER" : "Just a placeholder"
};
