/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_AbandonRequest_H_
#define	_AbandonRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageID.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AbandonRequest */
typedef MessageID_t	 AbandonRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AbandonRequest;
asn_struct_free_f AbandonRequest_free;
asn_struct_print_f AbandonRequest_print;
asn_constr_check_f AbandonRequest_constraint;
ber_type_decoder_f AbandonRequest_decode_ber;
der_type_encoder_f AbandonRequest_encode_der;
xer_type_decoder_f AbandonRequest_decode_xer;
xer_type_encoder_f AbandonRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AbandonRequest_H_ */
#include <asn_internal.h>
