/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_AddRequest_H_
#define	_AddRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPDN.h"
#include "AttributeList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AddRequest */
typedef struct AddRequest {
	LDAPDN_t	 entry;
	AttributeList_t	 attributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AddRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _AddRequest_H_ */
#include <asn_internal.h>
