/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_AssertionValue_H_
#define	_AssertionValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AssertionValue */
typedef OCTET_STRING_t	 AssertionValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssertionValue;
asn_struct_free_f AssertionValue_free;
asn_struct_print_f AssertionValue_print;
asn_constr_check_f AssertionValue_constraint;
ber_type_decoder_f AssertionValue_decode_ber;
der_type_encoder_f AssertionValue_encode_der;
xer_type_decoder_f AssertionValue_decode_xer;
xer_type_encoder_f AssertionValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AssertionValue_H_ */
#include <asn_internal.h>
