/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_Attribute_H_
#define	_Attribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeDescription.h"
#include "AttributeValue.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Attribute */
typedef struct Attribute {
	AttributeDescription_t	 type;
	struct Attribute__vals {
		A_SET_OF(AttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vals;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Attribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Attribute;

#ifdef __cplusplus
}
#endif

#endif	/* _Attribute_H_ */
#include <asn_internal.h>
