/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_AttributeDescription_H_
#define	_AttributeDescription_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeDescription */
typedef LDAPString_t	 AttributeDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeDescription;
asn_struct_free_f AttributeDescription_free;
asn_struct_print_f AttributeDescription_print;
asn_constr_check_f AttributeDescription_constraint;
ber_type_decoder_f AttributeDescription_decode_ber;
der_type_encoder_f AttributeDescription_encode_der;
xer_type_decoder_f AttributeDescription_decode_xer;
xer_type_encoder_f AttributeDescription_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeDescription_H_ */
#include <asn_internal.h>
