/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_AttributeTypeAndValues_H_
#define	_AttributeTypeAndValues_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeDescription.h"
#include "AttributeValue.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeTypeAndValues */
typedef struct AttributeTypeAndValues {
	AttributeDescription_t	 type;
	struct AttributeTypeAndValues__vals {
		A_SET_OF(AttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vals;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeTypeAndValues_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeTypeAndValues;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeTypeAndValues_H_ */
#include <asn_internal.h>
