/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "AuthenticationChoice.h"

static asn_TYPE_member_t asn_MBR_AuthenticationChoice_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticationChoice, choice.simple),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Simple,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"simple"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticationChoice, choice.sasl),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SaslCredentials,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sasl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticationChoice, choice.ntlmsspNegotiate),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ntlmsspNegotiate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticationChoice, choice.ntlmsspAuth),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ntlmsspAuth"
		},
};
static asn_TYPE_tag2member_t asn_MAP_AuthenticationChoice_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* simple at 140 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* sasl at 142 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 2, 0, 0 }, /* ntlmsspNegotiate at 144 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 3, 0, 0 } /* ntlmsspAuth at 145 */
};
static asn_CHOICE_specifics_t asn_SPC_AuthenticationChoice_specs_1 = {
	sizeof(struct AuthenticationChoice),
	offsetof(struct AuthenticationChoice, _asn_ctx),
	offsetof(struct AuthenticationChoice, present),
	sizeof(((struct AuthenticationChoice *)0)->present),
	asn_MAP_AuthenticationChoice_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticationChoice = {
	"AuthenticationChoice",
	"AuthenticationChoice",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_AuthenticationChoice_1,
	4,	/* Elements count */
	&asn_SPC_AuthenticationChoice_specs_1	/* Additional specs */
};

