/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_BindRequest_H_
#define	_BindRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LDAPDN.h"
#include "AuthenticationChoice.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BindRequest */
typedef struct BindRequest {
	long	 version;
	LDAPDN_t	 name;
	AuthenticationChoice_t	 authentication;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BindRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BindRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _BindRequest_H_ */
#include <asn_internal.h>
