/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "BindRequest.h"

static int
memb_version_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 127)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_BindRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BindRequest, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_version_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BindRequest, name),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_LDAPDN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BindRequest, authentication),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_AuthenticationChoice,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"authentication"
		},
};
static ber_tlv_tag_t asn_DEF_BindRequest_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BindRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 134 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* name at 135 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* simple at 140 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* sasl at 142 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 2, 0, 0 }, /* ntlmsspNegotiate at 144 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 2, 0, 0 } /* ntlmsspAuth at 145 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BindRequest_specs_1 = {
	sizeof(struct BindRequest),
	offsetof(struct BindRequest, _asn_ctx),
	asn_MAP_BindRequest_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BindRequest = {
	"BindRequest",
	"BindRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BindRequest_tags_1,
	sizeof(asn_DEF_BindRequest_tags_1)
		/sizeof(asn_DEF_BindRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_BindRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_BindRequest_tags_1)
		/sizeof(asn_DEF_BindRequest_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_BindRequest_1,
	3,	/* Elements count */
	&asn_SPC_BindRequest_specs_1	/* Additional specs */
};

