/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_CompareResponse_H_
#define	_CompareResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPResult.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CompareResponse */
typedef LDAPResult_t	 CompareResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CompareResponse;
asn_struct_free_f CompareResponse_free;
asn_struct_print_f CompareResponse_print;
asn_constr_check_f CompareResponse_constraint;
ber_type_decoder_f CompareResponse_decode_ber;
der_type_encoder_f CompareResponse_encode_der;
xer_type_decoder_f CompareResponse_decode_xer;
xer_type_encoder_f CompareResponse_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CompareResponse_H_ */
#include <asn_internal.h>
