/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_ControlType_H_
#define	_ControlType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPOID.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ControlType */
typedef LDAPOID_t	 ControlType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ControlType;
asn_struct_free_f ControlType_free;
asn_struct_print_f ControlType_print;
asn_constr_check_f ControlType_constraint;
ber_type_decoder_f ControlType_decode_ber;
der_type_encoder_f ControlType_encode_der;
xer_type_decoder_f ControlType_decode_xer;
xer_type_encoder_f ControlType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ControlType_H_ */
#include <asn_internal.h>
