/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_Controls_H_
#define	_Controls_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Control;

/* Controls */
typedef struct Controls {
	A_SEQUENCE_OF(struct Control) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Controls_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Controls;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Control.h"

#endif	/* _Controls_H_ */
#include <asn_internal.h>
