/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_DirSyncControlValue_H_
#define	_DirSyncControlValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DirSyncFlags.h"
#include <INTEGER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DirSyncControlValue */
typedef struct DirSyncControlValue {
	DirSyncFlags_t	 flags;
	INTEGER_t	 maxBytes;
	OCTET_STRING_t	 cookie;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DirSyncControlValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DirSyncControlValue;

#ifdef __cplusplus
}
#endif

#endif	/* _DirSyncControlValue_H_ */
#include <asn_internal.h>
