/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_DirSyncFlags_H_
#define	_DirSyncFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DirSyncFlags */
typedef INTEGER_t	 DirSyncFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DirSyncFlags;
asn_struct_free_f DirSyncFlags_free;
asn_struct_print_f DirSyncFlags_print;
asn_constr_check_f DirSyncFlags_constraint;
ber_type_decoder_f DirSyncFlags_decode_ber;
der_type_encoder_f DirSyncFlags_encode_der;
xer_type_decoder_f DirSyncFlags_decode_xer;
xer_type_encoder_f DirSyncFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DirSyncFlags_H_ */
#include <asn_internal.h>
