/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_ExtendedResponse_H_
#define	_ExtendedResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include "LDAPDN.h"
#include "ErrorMessage.h"
#include "ResponseName.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExtendedResponse__resultCode {
	ExtendedResponse__resultCode_success	= 0,
	ExtendedResponse__resultCode_operationsError	= 1,
	ExtendedResponse__resultCode_protocolError	= 2,
	ExtendedResponse__resultCode_timeLimitExceeded	= 3,
	ExtendedResponse__resultCode_sizeLimitExceeded	= 4,
	ExtendedResponse__resultCode_compareFalse	= 5,
	ExtendedResponse__resultCode_compareTrue	= 6,
	ExtendedResponse__resultCode_authMethodNotSupported	= 7,
	ExtendedResponse__resultCode_strongAuthRequired	= 8,
	ExtendedResponse__resultCode_referral	= 10,
	ExtendedResponse__resultCode_adminLimitExceeded	= 11,
	ExtendedResponse__resultCode_unavailableCriticalExtension	= 12,
	ExtendedResponse__resultCode_confidentialityRequired	= 13,
	ExtendedResponse__resultCode_saslBindInProgress	= 14,
	ExtendedResponse__resultCode_noSuchAttribute	= 16,
	ExtendedResponse__resultCode_undefinedAttributeType	= 17,
	ExtendedResponse__resultCode_inappropriateMatching	= 18,
	ExtendedResponse__resultCode_constraintViolation	= 19,
	ExtendedResponse__resultCode_attributeOrValueExists	= 20,
	ExtendedResponse__resultCode_invalidAttributeSyntax	= 21,
	ExtendedResponse__resultCode_noSuchObject	= 32,
	ExtendedResponse__resultCode_aliasProblem	= 33,
	ExtendedResponse__resultCode_invalidDNSyntax	= 34,
	ExtendedResponse__resultCode_aliasDereferencingProblem	= 36,
	ExtendedResponse__resultCode_inappropriateAuthentication	= 48,
	ExtendedResponse__resultCode_invalidCredentials	= 49,
	ExtendedResponse__resultCode_insufficientAccessRights	= 50,
	ExtendedResponse__resultCode_busy	= 51,
	ExtendedResponse__resultCode_unavailable	= 52,
	ExtendedResponse__resultCode_unwillingToPerform	= 53,
	ExtendedResponse__resultCode_loopDetect	= 54,
	ExtendedResponse__resultCode_namingViolation	= 64,
	ExtendedResponse__resultCode_objectClassViolation	= 65,
	ExtendedResponse__resultCode_notAllowedOnNonLeaf	= 66,
	ExtendedResponse__resultCode_notAllowedOnRDN	= 67,
	ExtendedResponse__resultCode_entryAlreadyExists	= 68,
	ExtendedResponse__resultCode_objectClassModsProhibited	= 69,
	ExtendedResponse__resultCode_affectsMultipleDSAs	= 71,
	ExtendedResponse__resultCode_other	= 80,
	ExtendedResponse__resultCode_canceled	= 118,
	ExtendedResponse__resultCode_noSuchOperation	= 119,
	ExtendedResponse__resultCode_tooLate	= 120,
	ExtendedResponse__resultCode_cannotCancel	= 121
} e_ExtendedResponse__resultCode;

/* Forward declarations */
struct Referral;

/* ExtendedResponse */
typedef struct ExtendedResponse {
	ENUMERATED_t	 resultCode;
	LDAPDN_t	 matchedDN;
	ErrorMessage_t	 errorMessage;
	struct Referral	*referral	/* OPTIONAL */;
	ResponseName_t	*responseName	/* OPTIONAL */;
	OCTET_STRING_t	*response	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedResponse_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_resultCode_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Referral.h"

#endif	/* _ExtendedResponse_H_ */
#include <asn_internal.h>
