/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_IntermediateResponse_H_
#define	_IntermediateResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResponseName.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntermediateResponse */
typedef struct IntermediateResponse {
	ResponseName_t	*responseName	/* OPTIONAL */;
	OCTET_STRING_t	*responseValue	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntermediateResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntermediateResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _IntermediateResponse_H_ */
#include <asn_internal.h>
