/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_LDAPOID_H_
#define	_LDAPOID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LDAPOID */
typedef OCTET_STRING_t	 LDAPOID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LDAPOID;
asn_struct_free_f LDAPOID_free;
asn_struct_print_f LDAPOID_print;
asn_constr_check_f LDAPOID_constraint;
ber_type_decoder_f LDAPOID_decode_ber;
der_type_encoder_f LDAPOID_encode_der;
xer_type_decoder_f LDAPOID_decode_xer;
xer_type_encoder_f LDAPOID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LDAPOID_H_ */
#include <asn_internal.h>
