/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "LDAPMessage.h"

static asn_TYPE_member_t asn_MBR_LDAPMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LDAPMessage, messageID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_MessageID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LDAPMessage, protocolOp),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ProtocolOp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocolOp"
		},
	{ ATF_POINTER, 1, offsetof(struct LDAPMessage, controls),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Controls,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"controls"
		},
};
static ber_tlv_tag_t asn_DEF_LDAPMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LDAPMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* messageID at 15 */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* bindRequest at 23 */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* bindResponse at 24 */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 }, /* unbindRequest at 25 */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 1, 0, 0 }, /* searchRequest at 26 */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 1, 0, 0 }, /* searchResEntry at 27 */
    { (ASN_TAG_CLASS_APPLICATION | (5 << 2)), 1, 0, 0 }, /* searchResDone at 28 */
    { (ASN_TAG_CLASS_APPLICATION | (6 << 2)), 1, 0, 0 }, /* modifyRequest at 30 */
    { (ASN_TAG_CLASS_APPLICATION | (7 << 2)), 1, 0, 0 }, /* modifyResponse at 31 */
    { (ASN_TAG_CLASS_APPLICATION | (8 << 2)), 1, 0, 0 }, /* addRequest at 32 */
    { (ASN_TAG_CLASS_APPLICATION | (9 << 2)), 1, 0, 0 }, /* addResponse at 33 */
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 1, 0, 0 }, /* delRequest at 34 */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 1, 0, 0 }, /* delResponse at 35 */
    { (ASN_TAG_CLASS_APPLICATION | (12 << 2)), 1, 0, 0 }, /* modDNRequest at 36 */
    { (ASN_TAG_CLASS_APPLICATION | (13 << 2)), 1, 0, 0 }, /* modDNResponse at 37 */
    { (ASN_TAG_CLASS_APPLICATION | (14 << 2)), 1, 0, 0 }, /* compareRequest at 38 */
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 1, 0, 0 }, /* compareResponse at 39 */
    { (ASN_TAG_CLASS_APPLICATION | (16 << 2)), 1, 0, 0 }, /* abandonRequest at 40 */
    { (ASN_TAG_CLASS_APPLICATION | (19 << 2)), 1, 0, 0 }, /* searchResRef at 29 */
    { (ASN_TAG_CLASS_APPLICATION | (23 << 2)), 1, 0, 0 }, /* extendedReq at 41 */
    { (ASN_TAG_CLASS_APPLICATION | (24 << 2)), 1, 0, 0 }, /* extendedResp at 42 */
    { (ASN_TAG_CLASS_APPLICATION | (25 << 2)), 1, 0, 0 }, /* intermediateResponse at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 } /* controls at 17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LDAPMessage_specs_1 = {
	sizeof(struct LDAPMessage),
	offsetof(struct LDAPMessage, _asn_ctx),
	asn_MAP_LDAPMessage_tag2el_1,
	23,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LDAPMessage = {
	"LDAPMessage",
	"LDAPMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LDAPMessage_tags_1,
	sizeof(asn_DEF_LDAPMessage_tags_1)
		/sizeof(asn_DEF_LDAPMessage_tags_1[0]), /* 1 */
	asn_DEF_LDAPMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_LDAPMessage_tags_1)
		/sizeof(asn_DEF_LDAPMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LDAPMessage_1,
	3,	/* Elements count */
	&asn_SPC_LDAPMessage_specs_1	/* Additional specs */
};

