/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_LDAPResult_H_
#define	_LDAPResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include "LDAPDN.h"
#include "ErrorMessage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LDAPResult__resultCode {
	LDAPResult__resultCode_success	= 0,
	LDAPResult__resultCode_operationsError	= 1,
	LDAPResult__resultCode_protocolError	= 2,
	LDAPResult__resultCode_timeLimitExceeded	= 3,
	LDAPResult__resultCode_sizeLimitExceeded	= 4,
	LDAPResult__resultCode_compareFalse	= 5,
	LDAPResult__resultCode_compareTrue	= 6,
	LDAPResult__resultCode_authMethodNotSupported	= 7,
	LDAPResult__resultCode_strongAuthRequired	= 8,
	LDAPResult__resultCode_referral	= 10,
	LDAPResult__resultCode_adminLimitExceeded	= 11,
	LDAPResult__resultCode_unavailableCriticalExtension	= 12,
	LDAPResult__resultCode_confidentialityRequired	= 13,
	LDAPResult__resultCode_saslBindInProgress	= 14,
	LDAPResult__resultCode_noSuchAttribute	= 16,
	LDAPResult__resultCode_undefinedAttributeType	= 17,
	LDAPResult__resultCode_inappropriateMatching	= 18,
	LDAPResult__resultCode_constraintViolation	= 19,
	LDAPResult__resultCode_attributeOrValueExists	= 20,
	LDAPResult__resultCode_invalidAttributeSyntax	= 21,
	LDAPResult__resultCode_noSuchObject	= 32,
	LDAPResult__resultCode_aliasProblem	= 33,
	LDAPResult__resultCode_invalidDNSyntax	= 34,
	LDAPResult__resultCode_aliasDereferencingProblem	= 36,
	LDAPResult__resultCode_inappropriateAuthentication	= 48,
	LDAPResult__resultCode_invalidCredentials	= 49,
	LDAPResult__resultCode_insufficientAccessRights	= 50,
	LDAPResult__resultCode_busy	= 51,
	LDAPResult__resultCode_unavailable	= 52,
	LDAPResult__resultCode_unwillingToPerform	= 53,
	LDAPResult__resultCode_loopDetect	= 54,
	LDAPResult__resultCode_namingViolation	= 64,
	LDAPResult__resultCode_objectClassViolation	= 65,
	LDAPResult__resultCode_notAllowedOnNonLeaf	= 66,
	LDAPResult__resultCode_notAllowedOnRDN	= 67,
	LDAPResult__resultCode_entryAlreadyExists	= 68,
	LDAPResult__resultCode_objectClassModsProhibited	= 69,
	LDAPResult__resultCode_affectsMultipleDSAs	= 71,
	LDAPResult__resultCode_other	= 80,
	LDAPResult__resultCode_canceled	= 118,
	LDAPResult__resultCode_noSuchOperation	= 119,
	LDAPResult__resultCode_tooLate	= 120,
	LDAPResult__resultCode_cannotCancel	= 121
} e_LDAPResult__resultCode;

/* Forward declarations */
struct Referral;

/* LDAPResult */
typedef struct LDAPResult {
	ENUMERATED_t	 resultCode;
	LDAPDN_t	 matchedDN;
	ErrorMessage_t	 errorMessage;
	struct Referral	*referral	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LDAPResult_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_resultCode_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LDAPResult;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Referral.h"

#endif	/* _LDAPResult_H_ */
#include <asn_internal.h>
