/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_LDAPMessage_H_
#define	_LDAPMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageID.h"
#include "ProtocolOp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Controls;

/* LDAPMessage */
typedef struct LDAPMessage {
	MessageID_t	 messageID;
	ProtocolOp_t	 protocolOp;
	struct Controls	*controls	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LDAPMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LDAPMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Controls.h"

#endif	/* _LDAPMessage_H_ */
#include <asn_internal.h>
