/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "MatchingRuleAssertion.h"

static asn_TYPE_member_t asn_MBR_MatchingRuleAssertion_1[] = {
	{ ATF_POINTER, 2, offsetof(struct MatchingRuleAssertion, matchingRule),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MatchingRuleId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"matchingRule"
		},
	{ ATF_POINTER, 1, offsetof(struct MatchingRuleAssertion, type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttributeDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MatchingRuleAssertion, matchValue),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AssertionValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"matchValue"
		},
	{ ATF_POINTER, 1, offsetof(struct MatchingRuleAssertion, dnAttributes),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dnAttributes"
		},
};
static ber_tlv_tag_t asn_DEF_MatchingRuleAssertion_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MatchingRuleAssertion_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* matchingRule at 259 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* type at 260 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* matchValue at 261 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 } /* dnAttributes at 262 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MatchingRuleAssertion_specs_1 = {
	sizeof(struct MatchingRuleAssertion),
	offsetof(struct MatchingRuleAssertion, _asn_ctx),
	asn_MAP_MatchingRuleAssertion_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MatchingRuleAssertion = {
	"MatchingRuleAssertion",
	"MatchingRuleAssertion",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MatchingRuleAssertion_tags_1,
	sizeof(asn_DEF_MatchingRuleAssertion_tags_1)
		/sizeof(asn_DEF_MatchingRuleAssertion_tags_1[0]), /* 1 */
	asn_DEF_MatchingRuleAssertion_tags_1,	/* Same as above */
	sizeof(asn_DEF_MatchingRuleAssertion_tags_1)
		/sizeof(asn_DEF_MatchingRuleAssertion_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MatchingRuleAssertion_1,
	4,	/* Elements count */
	&asn_SPC_MatchingRuleAssertion_specs_1	/* Additional specs */
};

