/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_MatchingRuleAssertion_H_
#define	_MatchingRuleAssertion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MatchingRuleId.h"
#include "AttributeDescription.h"
#include "AssertionValue.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MatchingRuleAssertion */
typedef struct MatchingRuleAssertion {
	MatchingRuleId_t	*matchingRule	/* OPTIONAL */;
	AttributeDescription_t	*type	/* OPTIONAL */;
	AssertionValue_t	 matchValue;
	BOOLEAN_t	*dnAttributes	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MatchingRuleAssertion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MatchingRuleAssertion;

#ifdef __cplusplus
}
#endif

#endif	/* _MatchingRuleAssertion_H_ */
#include <asn_internal.h>
