/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_ModifyRequest_H_
#define	_ModifyRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPDN.h"
#include <asn_SEQUENCE_OF.h>
#include <ENUMERATED.h>
#include "AttributeTypeAndValues.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum operation {
	operation_add	= 0,
	operation_delete	= 1,
	operation_replace	= 2
} e_operation;

struct ModifyRequest__modification__Member {
			ENUMERATED_t	 operation;
			AttributeTypeAndValues_t	 modification;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		};
        
/* ModifyRequest */
typedef struct ModifyRequest {
	LDAPDN_t	 object;
	struct ModifyRequest__modification {
		A_SEQUENCE_OF(struct ModifyRequest__modification__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModifyRequest_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_operation_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ModifyRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ModifyRequest_H_ */
#include <asn_internal.h>
