/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "ModifyDNRequest.h"

static asn_TYPE_member_t asn_MBR_ModifyDNRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ModifyDNRequest, entry),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_LDAPDN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"entry"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ModifyDNRequest, newrdn),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RelativeLDAPDN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"newrdn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ModifyDNRequest, deleteoldrdn),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"deleteoldrdn"
		},
	{ ATF_POINTER, 1, offsetof(struct ModifyDNRequest, newSuperior),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LDAPDN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"newSuperior"
		},
};
static ber_tlv_tag_t asn_DEF_ModifyDNRequest_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ModifyDNRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* deleteoldrdn at 311 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* entry at 309 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 0 }, /* newrdn at 310 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 } /* newSuperior at 312 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ModifyDNRequest_specs_1 = {
	sizeof(struct ModifyDNRequest),
	offsetof(struct ModifyDNRequest, _asn_ctx),
	asn_MAP_ModifyDNRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ModifyDNRequest = {
	"ModifyDNRequest",
	"ModifyDNRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ModifyDNRequest_tags_1,
	sizeof(asn_DEF_ModifyDNRequest_tags_1)
		/sizeof(asn_DEF_ModifyDNRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_ModifyDNRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModifyDNRequest_tags_1)
		/sizeof(asn_DEF_ModifyDNRequest_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ModifyDNRequest_1,
	4,	/* Elements count */
	&asn_SPC_ModifyDNRequest_specs_1	/* Additional specs */
};

