/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_PartialAttributeList_H_
#define	_PartialAttributeList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "AttributeDescription.h"
#include "AttributeValue.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

struct PartialAttributeList__Member {
		AttributeDescription_t	 type;
		struct patt_vals {
			A_SET_OF(AttributeValue_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} vals;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	};
    
/* PartialAttributeList */
typedef struct PartialAttributeList {
	A_SEQUENCE_OF(struct PartialAttributeList__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PartialAttributeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartialAttributeList;

#ifdef __cplusplus
}
#endif

#endif	/* _PartialAttributeList_H_ */
#include <asn_internal.h>
