/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "PasswordPolicyResponseValue.h"

static int
memb_timeBeforeExpiration_constraint_2(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_graceAuthNsRemaining_constraint_2(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
error_5_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
error_5_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
error_5_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	error_5_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
error_5_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	error_5_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
error_5_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	error_5_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
error_5_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	error_5_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
error_5_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	error_5_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
error_5_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	error_5_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_TYPE_member_t asn_MBR_warning_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PasswordPolicyResponseValue__warning, choice.timeBeforeExpiration),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_timeBeforeExpiration_constraint_2,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeBeforeExpiration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PasswordPolicyResponseValue__warning, choice.graceAuthNsRemaining),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_graceAuthNsRemaining_constraint_2,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"graceAuthNsRemaining"
		},
};
static asn_TYPE_tag2member_t asn_MAP_warning_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* timeBeforeExpiration at 525 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* graceAuthNsRemaining at 526 */
};
static asn_CHOICE_specifics_t asn_SPC_warning_specs_2 = {
	sizeof(struct PasswordPolicyResponseValue__warning),
	offsetof(struct PasswordPolicyResponseValue__warning, _asn_ctx),
	offsetof(struct PasswordPolicyResponseValue__warning, present),
	sizeof(((struct PasswordPolicyResponseValue__warning *)0)->present),
	asn_MAP_warning_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_warning_2 = {
	"warning",
	"warning",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_warning_2,
	2,	/* Elements count */
	&asn_SPC_warning_specs_2	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_error_value2enum_5[] = {
	{ 0,	15,	"passwordExpired" },
	{ 1,	13,	"accountLocked" },
	{ 2,	16,	"changeAfterReset" },
	{ 3,	21,	"passwordModNotAllowed" },
	{ 4,	21,	"mustSupplyOldPassword" },
	{ 5,	27,	"insufficientPasswordQuality" },
	{ 6,	16,	"passwordTooShort" },
	{ 7,	16,	"passwordTooYoung" },
	{ 8,	17,	"passwordInHistory" }
};
static unsigned int asn_MAP_error_enum2value_5[] = {
	1,	/* accountLocked(1) */
	2,	/* changeAfterReset(2) */
	5,	/* insufficientPasswordQuality(5) */
	4,	/* mustSupplyOldPassword(4) */
	0,	/* passwordExpired(0) */
	8,	/* passwordInHistory(8) */
	3,	/* passwordModNotAllowed(3) */
	6,	/* passwordTooShort(6) */
	7	/* passwordTooYoung(7) */
};
static asn_INTEGER_specifics_t asn_SPC_error_specs_5 = {
	asn_MAP_error_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_error_enum2value_5,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_error_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_error_5 = {
	"error",
	"error",
	error_5_free,
	error_5_print,
	error_5_constraint,
	error_5_decode_ber,
	error_5_encode_der,
	error_5_decode_xer,
	error_5_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_error_tags_5,
	sizeof(asn_DEF_error_tags_5)
		/sizeof(asn_DEF_error_tags_5[0]) - 1, /* 1 */
	asn_DEF_error_tags_5,	/* Same as above */
	sizeof(asn_DEF_error_tags_5)
		/sizeof(asn_DEF_error_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_error_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PasswordPolicyResponseValue_1[] = {
	{ ATF_POINTER, 2, offsetof(struct PasswordPolicyResponseValue, warning),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_warning_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"warning"
		},
	{ ATF_POINTER, 1, offsetof(struct PasswordPolicyResponseValue, error),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_error_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"error"
		},
};
static ber_tlv_tag_t asn_DEF_PasswordPolicyResponseValue_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PasswordPolicyResponseValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* warning at 525 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* error at 528 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PasswordPolicyResponseValue_specs_1 = {
	sizeof(struct PasswordPolicyResponseValue),
	offsetof(struct PasswordPolicyResponseValue, _asn_ctx),
	asn_MAP_PasswordPolicyResponseValue_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PasswordPolicyResponseValue = {
	"PasswordPolicyResponseValue",
	"PasswordPolicyResponseValue",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PasswordPolicyResponseValue_tags_1,
	sizeof(asn_DEF_PasswordPolicyResponseValue_tags_1)
		/sizeof(asn_DEF_PasswordPolicyResponseValue_tags_1[0]), /* 1 */
	asn_DEF_PasswordPolicyResponseValue_tags_1,	/* Same as above */
	sizeof(asn_DEF_PasswordPolicyResponseValue_tags_1)
		/sizeof(asn_DEF_PasswordPolicyResponseValue_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PasswordPolicyResponseValue_1,
	2,	/* Elements count */
	&asn_SPC_PasswordPolicyResponseValue_specs_1	/* Additional specs */
};

