/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_PasswordPolicyResponseValue_H_
#define	_PasswordPolicyResponseValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PasswordPolicyResponseValue__warning_PR {
	PasswordPolicyResponseValue__warning_PR_NOTHING,	/* No components present */
	PasswordPolicyResponseValue__warning_PR_timeBeforeExpiration,
	PasswordPolicyResponseValue__warning_PR_graceAuthNsRemaining
} PasswordPolicyResponseValue__warning_PR;
typedef enum PasswordPolicyResponseValue__error {
	PasswordPolicyResponseValue__error_passwordExpired	= 0,
	PasswordPolicyResponseValue__error_accountLocked	= 1,
	PasswordPolicyResponseValue__error_changeAfterReset	= 2,
	PasswordPolicyResponseValue__error_passwordModNotAllowed	= 3,
	PasswordPolicyResponseValue__error_mustSupplyOldPassword	= 4,
	PasswordPolicyResponseValue__error_insufficientPasswordQuality	= 5,
	PasswordPolicyResponseValue__error_passwordTooShort	= 6,
	PasswordPolicyResponseValue__error_passwordTooYoung	= 7,
	PasswordPolicyResponseValue__error_passwordInHistory	= 8
} e_PasswordPolicyResponseValue__error;

/* PasswordPolicyResponseValue */
typedef struct PasswordPolicyResponseValue {
	struct PasswordPolicyResponseValue__warning {
		PasswordPolicyResponseValue__warning_PR present;
		union PasswordPolicyResponseValue__warning_u {
			long	 timeBeforeExpiration;
			long	 graceAuthNsRemaining;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *warning;
	ENUMERATED_t	*error	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PasswordPolicyResponseValue_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_error_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PasswordPolicyResponseValue;

#ifdef __cplusplus
}
#endif

#endif	/* _PasswordPolicyResponseValue_H_ */
#include <asn_internal.h>
