/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_ProtocolOp_H_
#define	_ProtocolOp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BindRequest.h"
#include "BindResponse.h"
#include "UnbindRequest.h"
#include "SearchRequest.h"
#include "SearchResultEntry.h"
#include "SearchResultDone.h"
#include "SearchResultReference.h"
#include "ModifyRequest.h"
#include "ModifyResponse.h"
#include "AddRequest.h"
#include "AddResponse.h"
#include "DelRequest.h"
#include "DelResponse.h"
#include "ModifyDNRequest.h"
#include "ModifyDNResponse.h"
#include "CompareRequest.h"
#include "CompareResponse.h"
#include "AbandonRequest.h"
#include "ExtendedRequest.h"
#include "ExtendedResponse.h"
#include "IntermediateResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProtocolOp_PR {
	ProtocolOp_PR_NOTHING,	/* No components present */
	ProtocolOp_PR_bindRequest,
	ProtocolOp_PR_bindResponse,
	ProtocolOp_PR_unbindRequest,
	ProtocolOp_PR_searchRequest,
	ProtocolOp_PR_searchResEntry,
	ProtocolOp_PR_searchResDone,
	ProtocolOp_PR_searchResRef,
	ProtocolOp_PR_modifyRequest,
	ProtocolOp_PR_modifyResponse,
	ProtocolOp_PR_addRequest,
	ProtocolOp_PR_addResponse,
	ProtocolOp_PR_delRequest,
	ProtocolOp_PR_delResponse,
	ProtocolOp_PR_modDNRequest,
	ProtocolOp_PR_modDNResponse,
	ProtocolOp_PR_compareRequest,
	ProtocolOp_PR_compareResponse,
	ProtocolOp_PR_abandonRequest,
	ProtocolOp_PR_extendedReq,
	ProtocolOp_PR_extendedResp,
	ProtocolOp_PR_intermediateResponse
} ProtocolOp_PR;

/* ProtocolOp */
typedef struct ProtocolOp {
	ProtocolOp_PR present;
	union ProtocolOp_u {
		BindRequest_t	 bindRequest;
		BindResponse_t	 bindResponse;
		UnbindRequest_t	 unbindRequest;
		SearchRequest_t	 searchRequest;
		SearchResultEntry_t	 searchResEntry;
		SearchResultDone_t	 searchResDone;
		SearchResultReference_t	 searchResRef;
		ModifyRequest_t	 modifyRequest;
		ModifyResponse_t	 modifyResponse;
		AddRequest_t	 addRequest;
		AddResponse_t	 addResponse;
		DelRequest_t	 delRequest;
		DelResponse_t	 delResponse;
		ModifyDNRequest_t	 modDNRequest;
		ModifyDNResponse_t	 modDNResponse;
		CompareRequest_t	 compareRequest;
		CompareResponse_t	 compareResponse;
		AbandonRequest_t	 abandonRequest;
		ExtendedRequest_t	 extendedReq;
		ExtendedResponse_t	 extendedResp;
		IntermediateResponse_t	 intermediateResponse;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolOp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolOp;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolOp_H_ */
#include <asn_internal.h>
