/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "ProtocolOp.h"

static asn_TYPE_member_t asn_MBR_ProtocolOp_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.bindRequest),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_BindRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bindRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.bindResponse),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_BindResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bindResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.unbindRequest),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_UnbindRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unbindRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.searchRequest),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_SearchRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"searchRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.searchResEntry),
		(ASN_TAG_CLASS_APPLICATION | (4 << 2)),
		0,
		&asn_DEF_SearchResultEntry,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"searchResEntry"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.searchResDone),
		(ASN_TAG_CLASS_APPLICATION | (5 << 2)),
		0,
		&asn_DEF_SearchResultDone,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"searchResDone"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.searchResRef),
		(ASN_TAG_CLASS_APPLICATION | (19 << 2)),
		0,
		&asn_DEF_SearchResultReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"searchResRef"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.modifyRequest),
		(ASN_TAG_CLASS_APPLICATION | (6 << 2)),
		0,
		&asn_DEF_ModifyRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modifyRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.modifyResponse),
		(ASN_TAG_CLASS_APPLICATION | (7 << 2)),
		0,
		&asn_DEF_ModifyResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modifyResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.addRequest),
		(ASN_TAG_CLASS_APPLICATION | (8 << 2)),
		0,
		&asn_DEF_AddRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"addRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.addResponse),
		(ASN_TAG_CLASS_APPLICATION | (9 << 2)),
		0,
		&asn_DEF_AddResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"addResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.delRequest),
		(ASN_TAG_CLASS_APPLICATION | (10 << 2)),
		0,
		&asn_DEF_DelRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"delRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.delResponse),
		(ASN_TAG_CLASS_APPLICATION | (11 << 2)),
		0,
		&asn_DEF_DelResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"delResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.modDNRequest),
		(ASN_TAG_CLASS_APPLICATION | (12 << 2)),
		0,
		&asn_DEF_ModifyDNRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modDNRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.modDNResponse),
		(ASN_TAG_CLASS_APPLICATION | (13 << 2)),
		0,
		&asn_DEF_ModifyDNResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modDNResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.compareRequest),
		(ASN_TAG_CLASS_APPLICATION | (14 << 2)),
		0,
		&asn_DEF_CompareRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"compareRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.compareResponse),
		(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
		0,
		&asn_DEF_CompareResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"compareResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.abandonRequest),
		(ASN_TAG_CLASS_APPLICATION | (16 << 2)),
		0,
		&asn_DEF_AbandonRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"abandonRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.extendedReq),
		(ASN_TAG_CLASS_APPLICATION | (23 << 2)),
		0,
		&asn_DEF_ExtendedRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extendedReq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.extendedResp),
		(ASN_TAG_CLASS_APPLICATION | (24 << 2)),
		0,
		&asn_DEF_ExtendedResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extendedResp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtocolOp, choice.intermediateResponse),
		(ASN_TAG_CLASS_APPLICATION | (25 << 2)),
		0,
		&asn_DEF_IntermediateResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"intermediateResponse"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ProtocolOp_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* bindRequest at 23 */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* bindResponse at 24 */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 2, 0, 0 }, /* unbindRequest at 25 */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 3, 0, 0 }, /* searchRequest at 26 */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 4, 0, 0 }, /* searchResEntry at 27 */
    { (ASN_TAG_CLASS_APPLICATION | (5 << 2)), 5, 0, 0 }, /* searchResDone at 28 */
    { (ASN_TAG_CLASS_APPLICATION | (6 << 2)), 7, 0, 0 }, /* modifyRequest at 30 */
    { (ASN_TAG_CLASS_APPLICATION | (7 << 2)), 8, 0, 0 }, /* modifyResponse at 31 */
    { (ASN_TAG_CLASS_APPLICATION | (8 << 2)), 9, 0, 0 }, /* addRequest at 32 */
    { (ASN_TAG_CLASS_APPLICATION | (9 << 2)), 10, 0, 0 }, /* addResponse at 33 */
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 11, 0, 0 }, /* delRequest at 34 */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 12, 0, 0 }, /* delResponse at 35 */
    { (ASN_TAG_CLASS_APPLICATION | (12 << 2)), 13, 0, 0 }, /* modDNRequest at 36 */
    { (ASN_TAG_CLASS_APPLICATION | (13 << 2)), 14, 0, 0 }, /* modDNResponse at 37 */
    { (ASN_TAG_CLASS_APPLICATION | (14 << 2)), 15, 0, 0 }, /* compareRequest at 38 */
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 16, 0, 0 }, /* compareResponse at 39 */
    { (ASN_TAG_CLASS_APPLICATION | (16 << 2)), 17, 0, 0 }, /* abandonRequest at 40 */
    { (ASN_TAG_CLASS_APPLICATION | (19 << 2)), 6, 0, 0 }, /* searchResRef at 29 */
    { (ASN_TAG_CLASS_APPLICATION | (23 << 2)), 18, 0, 0 }, /* extendedReq at 41 */
    { (ASN_TAG_CLASS_APPLICATION | (24 << 2)), 19, 0, 0 }, /* extendedResp at 42 */
    { (ASN_TAG_CLASS_APPLICATION | (25 << 2)), 20, 0, 0 } /* intermediateResponse at 44 */
};
static asn_CHOICE_specifics_t asn_SPC_ProtocolOp_specs_1 = {
	sizeof(struct ProtocolOp),
	offsetof(struct ProtocolOp, _asn_ctx),
	offsetof(struct ProtocolOp, present),
	sizeof(((struct ProtocolOp *)0)->present),
	asn_MAP_ProtocolOp_tag2el_1,
	21,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolOp = {
	"ProtocolOp",
	"ProtocolOp",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolOp_1,
	21,	/* Elements count */
	&asn_SPC_ProtocolOp_specs_1	/* Additional specs */
};

