/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_RelativeLDAPDN_H_
#define	_RelativeLDAPDN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RelativeLDAPDN */
typedef LDAPString_t	 RelativeLDAPDN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelativeLDAPDN;
asn_struct_free_f RelativeLDAPDN_free;
asn_struct_print_f RelativeLDAPDN_print;
asn_constr_check_f RelativeLDAPDN_constraint;
ber_type_decoder_f RelativeLDAPDN_decode_ber;
der_type_encoder_f RelativeLDAPDN_encode_der;
xer_type_decoder_f RelativeLDAPDN_decode_xer;
xer_type_encoder_f RelativeLDAPDN_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RelativeLDAPDN_H_ */
#include <asn_internal.h>
