/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_ResponseName_H_
#define	_ResponseName_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPOID.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ResponseName */
typedef LDAPOID_t	 ResponseName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseName;
asn_struct_free_f ResponseName_free;
asn_struct_print_f ResponseName_print;
asn_constr_check_f ResponseName_constraint;
ber_type_decoder_f ResponseName_decode_ber;
der_type_encoder_f ResponseName_encode_der;
xer_type_decoder_f ResponseName_decode_xer;
xer_type_encoder_f ResponseName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseName_H_ */
#include <asn_internal.h>
