/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_SaslCredentials_H_
#define	_SaslCredentials_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Mechanism.h"
#include "Credentials.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SaslCredentials */
typedef struct SaslCredentials {
	Mechanism_t	 mechanism;
	Credentials_t	*credentials	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SaslCredentials_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SaslCredentials;

#ifdef __cplusplus
}
#endif

#endif	/* _SaslCredentials_H_ */
#include <asn_internal.h>
