/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_SearchControlValue_H_
#define	_SearchControlValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SearchControlValue */
typedef struct SearchControlValue {
	INTEGER_t	 size;
	OCTET_STRING_t	 cookie;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SearchControlValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SearchControlValue;

#ifdef __cplusplus
}
#endif

#endif	/* _SearchControlValue_H_ */
#include <asn_internal.h>
