/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_SearchResultReference_H_
#define	_SearchResultReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPURL.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SearchResultReference */
typedef struct SearchResultReference {
	A_SEQUENCE_OF(LDAPURL_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SearchResultReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SearchResultReference;

#ifdef __cplusplus
}
#endif

#endif	/* _SearchResultReference_H_ */
#include <asn_internal.h>
