/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_ServerSaslCreds_H_
#define	_ServerSaslCreds_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServerSaslCreds */
typedef OCTET_STRING_t	 ServerSaslCreds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServerSaslCreds;
asn_struct_free_f ServerSaslCreds_free;
asn_struct_print_f ServerSaslCreds_print;
asn_constr_check_f ServerSaslCreds_constraint;
ber_type_decoder_f ServerSaslCreds_decode_ber;
der_type_encoder_f ServerSaslCreds_encode_der;
xer_type_decoder_f ServerSaslCreds_decode_xer;
xer_type_encoder_f ServerSaslCreds_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServerSaslCreds_H_ */
#include <asn_internal.h>
