/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_Simple_H_
#define	_Simple_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Simple */
typedef OCTET_STRING_t	 Simple_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Simple;
asn_struct_free_f Simple_free;
asn_struct_print_f Simple_print;
asn_constr_check_f Simple_constraint;
ber_type_decoder_f Simple_decode_ber;
der_type_encoder_f Simple_encode_der;
xer_type_decoder_f Simple_decode_xer;
xer_type_encoder_f Simple_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Simple_H_ */
#include <asn_internal.h>
