/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_SyncStateValue_H_
#define	_SyncStateValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include "SyncUUID.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SyncStateValue__state {
	SyncStateValue__state_present	= 0,
	SyncStateValue__state_add	= 1,
	SyncStateValue__state_modify	= 2,
	SyncStateValue__state_delete	= 3
} e_SyncStateValue__state;

/* SyncStateValue */
typedef struct SyncStateValue {
	ENUMERATED_t	 state;
	SyncUUID_t	 entryUUID;
	OCTET_STRING_t	*cookie	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SyncStateValue_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_state_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SyncStateValue;

#ifdef __cplusplus
}
#endif

#endif	/* _SyncStateValue_H_ */
#include <asn_internal.h>
