/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#include "SyncDoneValue.h"

static asn_TYPE_member_t asn_MBR_SyncDoneValue_1[] = {
	{ ATF_POINTER, 2, offsetof(struct SyncDoneValue, cookie),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cookie"
		},
	{ ATF_POINTER, 1, offsetof(struct SyncDoneValue, refreshDeletes),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"refreshDeletes"
		},
};
static ber_tlv_tag_t asn_DEF_SyncDoneValue_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SyncDoneValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, 0, 0 }, /* refreshDeletes at 492 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 } /* cookie at 491 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SyncDoneValue_specs_1 = {
	sizeof(struct SyncDoneValue),
	offsetof(struct SyncDoneValue, _asn_ctx),
	asn_MAP_SyncDoneValue_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SyncDoneValue = {
	"SyncDoneValue",
	"SyncDoneValue",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SyncDoneValue_tags_1,
	sizeof(asn_DEF_SyncDoneValue_tags_1)
		/sizeof(asn_DEF_SyncDoneValue_tags_1[0]), /* 1 */
	asn_DEF_SyncDoneValue_tags_1,	/* Same as above */
	sizeof(asn_DEF_SyncDoneValue_tags_1)
		/sizeof(asn_DEF_SyncDoneValue_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SyncDoneValue_1,
	2,	/* Elements count */
	&asn_SPC_SyncDoneValue_specs_1	/* Additional specs */
};

