/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_SyncDoneValue_H_
#define	_SyncDoneValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SyncDoneValue */
typedef struct SyncDoneValue {
	OCTET_STRING_t	*cookie	/* OPTIONAL */;
	BOOLEAN_t	*refreshDeletes	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SyncDoneValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SyncDoneValue;

#ifdef __cplusplus
}
#endif

#endif	/* _SyncDoneValue_H_ */
#include <asn_internal.h>
