/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "simple_ldap_asn1.asn"
 */

#ifndef	_SyncInfoValue_H_
#define	_SyncInfoValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>
#include "SyncUUID.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SyncInfoValue_PR {
	SyncInfoValue_PR_NOTHING,	/* No components present */
	SyncInfoValue_PR_newcookie,
	SyncInfoValue_PR_refreshDelete,
	SyncInfoValue_PR_refreshPresent,
	SyncInfoValue_PR_syncIdSet
} SyncInfoValue_PR;

/* SyncInfoValue */
typedef struct SyncInfoValue {
	SyncInfoValue_PR present;
	union SyncInfoValue_u {
		OCTET_STRING_t	 newcookie;
		struct SyncInfoValue__refreshDelete {
			OCTET_STRING_t	*cookie	/* OPTIONAL */;
			BOOLEAN_t	*refreshDone	/* DEFAULT TRUE */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} refreshDelete;
		struct SyncInfoValue__refreshPresent {
			OCTET_STRING_t	*cookie	/* OPTIONAL */;
			BOOLEAN_t	*refreshDone	/* DEFAULT TRUE */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} refreshPresent;
		struct SyncInfoValue__syncIdSet {
			OCTET_STRING_t	*cookie	/* OPTIONAL */;
			BOOLEAN_t	*refreshDeletes	/* DEFAULT FALSE */;
			struct SyncInfoValue__syncIdSet__syncUUIDs {
				A_SET_OF(SyncUUID_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} syncUUIDs;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} syncIdSet;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SyncInfoValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SyncInfoValue;

#ifdef __cplusplus
}
#endif

#endif	/* _SyncInfoValue_H_ */
#include <asn_internal.h>
