#!/bin/bash
#
#	Copyright (c) openheap, uplusware
#	uplusware@gmail.com
#
if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi
path=$(dirname $0)
oldpwd=$(pwd)
cd ${path}
path=$(pwd)

if [ $# = 1 ]
then
	${path}/eriseutil -d $1 
else
	echo "Usage:erisedeluser username"
fi

cd ${oldpwd}
