#!/bin/bash

if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi
path=$(dirname $0)
oldpwd=$(pwd)
cd ${path}
path=$(pwd)

if [ $# = 2 ]
then
	${path}/eriseutil -A $1 $2
else
	echo "Usage:eriseaddusertogroup username groupname"
fi
cd ${oldpwd}