#!/bin/bash
#
#	Copyright (c) openheap, uplusware
#	uplusware@gmail.com
#

if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi
path=$(dirname $0)
oldpwd=$(pwd)
cd ${path}
path=$(pwd)

if [ $# = 3 ]
then
	${path}/eriseutil -a $1 $2 $3 -u -U
elif [ $# = 2 ]
then
	${path}/eriseutil -a $1 $2 -u -U
	
else
	echo "Usage:eriseadduser username password alias"
fi
cd ${oldpwd}