LANG_ID = "zh_cn"
LANG_DESC = "简体中文"
LANG_RESOURCE = {
	"LANG_RESOURCE_EXAMPLE" : "这是一个例子",
	"NOT_CHOOSE_ATTACH" : "请选择要上传的附件",
	"LOGIN_FAILED" : "认证失败",
	"MAILBOX_INBOX" : "收件箱",
	"MAILBOX_SENT" : "已发送邮件",
	"MAILBOX_DRAFTS" : "草稿箱",
	"MAILBOX_TRASH" : "废件箱",
	"MAILBOX_JUNK" : "垃圾邮件",
	"CONFIRM_CLEAN_TRASH" : "确实要清空废件箱吗？",
	"CLEAN_TRASH" : "清空",
	"SAVED" : "保存成功",
	"WRONG_VERIFIED_PASSWORD" : "新密码两次输入不一致",
	"PASSWORD_CHANGED_NEED_RELOGIN" : "密码更改成功，请重新登陆",
	"PASSWORD_CHANGED_FAILED_NEED_RETRY" : "密码更改失败，请重新操作",
	"EMPTY_ALIAS" : "别名不能为空",
	"CHANGE_ALIAS_OK" : "更改别名成功",
	"CHANGE_ALIAS_FAILED" : "更改别名失败",
	"ADMINISTRATOR_DESC" : "管理员",
	"USER_DESC" : "普通用户",
	"DISABLED_ID_DESC" : "禁用",
	"UNKNOWN_ID_DESC" : "未知",
	"YES" : "是",
	"NO" : "否",
	"LANG_RESOURCE_LAST_PLACE_HOLDER" : "占位符，无他途"
};
